name: NodeBBIntegration
main: com.yaricraft.nodebbintegration.NodeBBIntegration
version: 0.7.0-beta.3
depend: [Vault]
softdepend: [OnTime, Votifier, VanishNoPacket]
commands:
  register:
    description: Register your Minecraft account with your forum account.
    usage: /register [email] [password]
  nodebb:
    description: NodeBB Integration parent command.
    usage: /nodebb
    permission: nodebb.admin
