name: NodeBB Integration
main: com.yaricraft.nodebbintegration.NodeBBIntegration
version: 0.1.0
softdepend: [Vault]
commands:
  register:
    description: Register your Minecraft account on NodeBB.
    usage: /register [email] [password]
  nodebb:
    description: Reload NodeBB integration.
    usage: /nodebb
