name: NodeBB Integration
main: com.yaricraft.nodebbintegration.NodeBBIntegration
version: 0.6.0
softdepend: [Vault]
commands:
  register:
    description: Register your Minecraft account with your forum account.
    usage: /register [email] [password]
  nodebb:
    description: Reload NodeBB Integration.
    usage: /nodebb
    permission: nodebb.admin
