name: NodeBBIntegration
main: com.yaricraft.nodebbintegration.NodeBBIntegration
version: 0.6.2
depend: [Vault]
softdepend: [OnTime, Votifier]
commands:
  register:
    description: Register your Minecraft account with your forum account.
    usage: /register [email] [password]
  nodebb:
    description: Reload NodeBB Integration.
    usage: /nodebb
    permission: nodebb.admin
