---
FORUMURL: https://community.example.com/
FORUMNAME: My Minecraft Forum
APIKEY: SECRETPASSWORD
SOCKETNAMESPACE: plugins
PLUGINID: MinecraftIntegration
socketio:
    address: "https://live.example.com/"
    transports: ["polling", "websocket"]
messages:
    nodebb:
        live:
            get:
                - "The websocket domain is set to %live%"
            set:
                - "Set the websocket domain to %live%"
        transport:
            get:
                - "Websocket transports are %transports%"
            add:
                - "Removed websocket transport %transport%"
version: "0.7.0-beta.12"
PluginMessages:
    NodeBB:
        Help:
            - "&f[&6NodeBB Integration&f]"
            - "&4=&c=&6=&e=&a=&3=&b=&9=&1=&d=&5=&4=&c=&6=&e=&a=&2=&3=&b="
            - "&fCommands:"
            - "&e/nodebb reload &r- Reloads config and reconnects to the forum."
            - "&e/nodebb key [key] &r- Get or set the forum API key."
            - "&e/nodebb name [name] &r- Get or set the forum name."
            - "&e/nodebb url [url] &r- Get or set the forum url."
            - "&e/nodebb debug &r- Displays information useful for fixing errors."
    Register:
        Alert:
            - "Registering your player on %forumname% (%forumurl%&r)"
        NotConnected:
            - "Sorry! The server isn't currently connected to the forum."
        AssertParameters:
            - "Copy your player key from"
            - "$1minecraft/register&r"
            - "then use the command /register [key]"
        RegSuccess:
            - "Success! Registered your player on %forumname%"
        CreatedNewAccount:
            - "Success! Created a new account on %forumname%"
        FailKey:
            - "Invalid Key"
        FailDB:
            - "Error on forum. Please inform an administrator."
        BadRes:
            - "Internal error. Please inform an administrator."
        FailData:
            - "Data error. Please inform an administrator."
        ParsingError:
            - "Parsing error. Please inform an administrator."