name: NodeBBIntegration
main: com.radiofreederp.nodebbintegration.NodeBBIntegrationBukkit
version: 0.7.3.1
depend: [Vault]
softdepend: [OnTime, Votifier, VanishNoPacket]
commands:
  nodebb:
    description: NodeBB Integration parent command.
    permission: nodebb.admin
  register:
    description: Register your Minecraft account with your forum account.
